// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQsbmvx2Oo7nC5nRm19A3PsC-zBRF2ys0',
    appId: '1:368205316585:web:fec60bca5223afd80a4b78',
    messagingSenderId: '368205316585',
    projectId: 'movieapp-34910',
    authDomain: 'movieapp-34910.firebaseapp.com',
    storageBucket: 'movieapp-34910.appspot.com',
    measurementId: 'G-75M43PYHWS',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1wIZHaRo1P7xDkUhJtNMVOjFJxbemm5k',
    appId: '1:368205316585:ios:5470f7db72ce5cf50a4b78',
    messagingSenderId: '368205316585',
    projectId: 'movieapp-34910',
    storageBucket: 'movieapp-34910.appspot.com',
    iosBundleId: 'com.example.movieApp',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpqS3RM_andpV9E8RnbT4qnYhFvkZLhPc',
    appId: '1:368205316585:android:c60ca9cc806006690a4b78',
    messagingSenderId: '368205316585',
    projectId: 'movieapp-34910',
    storageBucket: 'movieapp-34910.appspot.com',
  );

}